component_depth: 1
languages:
- java
exclude:
- ./ArtOfIllusion/.*
- ./HelpPlugin/.*
- ./HelpPlugin/AOIHelp/.*
- ./HelpPlugin/AOIHelp/de/.*
- ./HelpPlugin/AOIHelp/fr/.*
- ./HelpPlugin/AOIHelp/helpset/.*
- ./HelpPlugin/AOIHelp/helpset/CmdReference/.*
- ./HelpPlugin/AOIHelp/helpset/FurtherHelp/.*
- ./HelpPlugin/AOIHelp/helpset/GettingStarted/.*
- ./HelpPlugin/AOIHelp/helpset/GettingStarted/images/.*
- ./HelpPlugin/AOIHelp/helpset/HowTo/.*
- ./HelpPlugin/AOIHelp/helpset/JavaHelpSearch/.*
- ./HelpPlugin/AOIHelp/helpset/Overview/.*
- ./HelpPlugin/AOIHelp/helpset/Overview/images/.*
- ./HelpPlugin/AOIHelp/helpset/TroubleShooting/.*
- ./HelpPlugin/AOIHelp/helpset/Tutorials/.*
- ./HelpPlugin/AOIHelp/helpset/Tutorials/HourGlass/.*
- ./HelpPlugin/AOIHelp/helpset/Tutorials/HourGlass/images/.*
- ./HelpPlugin/AOIHelp/helpset/images/.*
- ./HelpPlugin/lib/.*
- ./HelpPlugin/license/.*
- ./OSSpecific/.*
- ./PostInstall/.*
- ./Renderers/.*
- ./SPManager/.*
- ./Tests/.*
- ./Tools/.*
- ./Translators/.*
- ./bin/.*
- ./bin/artofillusion/.*
- ./bin/artofillusion/Icons/.*
- ./bin/artofillusion/Icons/selected/.*
- ./bin/artofillusion/animation/.*
- ./bin/artofillusion/animation/distortion/.*
- ./bin/artofillusion/image/.*
- ./bin/artofillusion/image/filter/.*
- ./bin/artofillusion/keystroke/.*
- ./bin/artofillusion/material/.*
- ./bin/artofillusion/math/.*
- ./bin/artofillusion/object/.*
- ./bin/artofillusion/osspecific/.*
- ./bin/artofillusion/procedural/.*
- ./bin/artofillusion/raster/.*
- ./bin/artofillusion/raytracer/.*
- ./bin/artofillusion/script/.*
- ./bin/artofillusion/spmanager/.*
- ./bin/artofillusion/spmanager/icons/.*
- ./bin/artofillusion/spmanager/postinstall/.*
- ./bin/artofillusion/texture/.*
- ./bin/artofillusion/titleImages/.*
- ./bin/artofillusion/tools/.*
- ./bin/artofillusion/translators/.*
- ./bin/artofillusion/ui/.*
- ./bin/artofillusion/ui/manipulatorIcons/.*
- ./bin/artofillusion/util/.*
- ./bin/artofillusion/view/.*
- ./lib/.*
